INSERT INTO Comerciantes (Avatar, Nombre_empresa, Contrasenia, Correo, Telefono, Direccion)
VALUES
    ('https://yt3.googleusercontent.com/9WgVvMb5NkRQeC2Oeu0WL9t7phgInjMq1zju6TZsvT5nLaCO9lALk_-GnL7UjsB_bo4aEbMi4g=s900-c-k-c0x00ffffff-no-rj', 'GAME', '6ca5cab77e702c787b4c14b3d3bf26bad43da606be6eed04ab0b9720120ae081', 'game@game.es', '938706714', 'Zaramaga Kalea, 1, 01013 Gasteiz'),
    ('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA8Ztdbr2gx2jV953PRCt2oxJFbSGr8g5Y-xLh3xWhag&s', 'GEMETIK Soluciones Tecnologicas', '961b6dd3ede3cb8ecbaacbd68de040cd78eb2ed5889130cceb4c49268ea4d506', 'gemetik@gmail.com', '945009120', 'Adriano VI Kalea, 5, 01008 Gasteiz'),
    ('https://brandemia.org/contenido/subidas/2019/04/ikea-nuevo-logo.jpg', 'Ikea', '12345', 'ikea@gmail.com', '123456789', 'Zaramaga Kalea, 1, 01013 Gasteiz'),
    ('https://www.smaver.es/wp-content/uploads/2018/08/logo-mercadona-2.jpg', 'Mercadona', '12345', 'mercaadona@gmail.com', '873239127', 'Sierra de Andia Kalea, 10, 01010 Gasteiz'),
    ('https://2.bp.blogspot.com/-66tJSY-P-tk/Wd-fsBKy4dI/AAAAAAAAAnk/ZGUJF6V-ikwXGKTJ1vVHhpVkWbdedupPgCLcBGAs/w1200-h630-p-k-no-nu/decathlon.gif', 'Decathlon', '12345', 'Decathlon@gmail.com', '284328574', 'General Alava Kalea, 32, 01005 Gasteiz');


-- Inserciones para las columnas Titulo, Precio, Descripcion, e ID_Comerciante (ID_Comerciante limitado a 1 y 2)
INSERT INTO Productos (Titulo, Precio, Descripcion, ID_Comerciante)
VALUES
    ('Ordenador de torre', 219.99, 'Potente ordenador de torre diseñado para gamers y profesionales. Equipado con procesador Intel Core i7, 16GB de RAM y tarjeta gráfica NVIDIA GeForce RTX 3080.', 1),
    ('Portátil', 24.99, 'Portátil ligero y versátil para uso diario. Pantalla de 14 pulgadas, procesador AMD Ryzen 5, 8GB de RAM y almacenamiento SSD de 256GB.', 1),
    ('PlayStation 5', 399.99, 'La consola de nueva generación de Sony con capacidad para juegos en 4K. Incluye un controlador DualSense con retroalimentación háptica para una experiencia inmersiva.', 1),
    ('Nintendo Switch', 129.99, 'Consola híbrida que se puede usar como consola de sobremesa o portátil. Incluye dos controles Joy-Con y es compatible con una amplia variedad de juegos.', 1),
    ('PlayStation 4', 299.99, 'Consola de juegos popular con biblioteca extensa de títulos. Incluye un controlador inalámbrico DualShock 4 y capacidad para transmitir contenido multimedia.', 1),
    ('Portátil MSI', 199.99, 'Portátil de alta gama para juegos con pantalla de 15.6 pulgadas, procesador Intel Core i5, 16GB de RAM y tarjeta gráfica NVIDIA GTX 1660 Ti.', 1),
    ('Nintendo3DS', 12.99, 'Consola portátil Nintendo 3DS con pantalla 3D sin necesidad de gafas. Incluye dos pantallas, cámara integrada y compatibilidad con juegos clásicos de Nintendo.', 1),
    ('MAC', 27.99, 'Sistema operativo macOS diseñado para computadoras Mac. Incluye una interfaz intuitiva, seguridad avanzada y compatibilidad con software creativo.', 1),
    ('PlayStation 3', 34.99, 'Consola de juegos clásica con una biblioteca impresionante de títulos. Incluye un controlador inalámbrico DualShock 3 y capacidad para reproducción de Blu-ray.', 1),
    ('Videojuego PS5', 21.99, 'Último título de aventuras para PlayStation 5. Gráficos asombrosos, jugabilidad envolvente y una historia cautivadora que te mantendrá entretenido durante horas.', 1),
    ('PlayStation 5', 399.99, 'La consola de nueva generación de Sony con capacidad para juegos en 4K. Incluye un controlador DualSense con retroalimentación háptica para una experiencia inmersiva.', 2),
    ('Tablet Android', 149.99, 'Tablet Android de 10 pulgadas con procesador rápido, 64GB de almacenamiento y una pantalla de alta resolución. Perfecta para entretenimiento y productividad.', 2),
    ('Smartphone Samsung', 299.99, 'Potente smartphone Samsung con pantalla AMOLED de 6.5 pulgadas, cámara triple de 48MP y batería de larga duración. Rendimiento excepcional para multitarea.', 2),
    ('Teclado Mecánico', 79.99, 'Teclado mecánico RGB con interruptores Cherry MX. Diseño duradero y retroiluminación personalizable para una experiencia de escritura y juego óptima.', 2),
    ('Auriculares Inalámbricos', 49.99, 'Auriculares inalámbricos con cancelación de ruido para una experiencia auditiva inmersiva. Batería de larga duración y cómodos para uso prolongado.', 2),
    ('Monitor Gaming', 329.99, 'Monitor gaming de 27 pulgadas con frecuencia de actualización de 144Hz y resolución QHD. Colores vibrantes y tiempo de respuesta rápido para una experiencia de juego suave.', 2),
    ('Cámara DSLR', 799.99, 'Cámara DSLR profesional con sensor de imagen de alta resolución y capacidad para grabación de video en 4K. Ideal para fotógrafos y cineastas.', 1),
    ('Impresora Multifunción', 129.99, 'Impresora multifunción con escáner y copiadora integrados. Conectividad inalámbrica y fácil integración con dispositivos móviles para imprimir desde cualquier lugar.', 1),
    ('Silla de Oficina', 149.99, 'Silla de oficina ergonómica con soporte lumbar y ajuste de altura. Diseño elegante y cómodo para largas horas de trabajo.', 1),
    ('Horno Eléctrico', 199.99, 'Horno eléctrico de convección con capacidad para asar, hornear y tostar. Control digital y múltiples funciones para cocinar con precisión.', 1),
    ('Licuadora', 49.99, 'Licuadora potente con motor de alto rendimiento. Perfecta para hacer batidos, jugos y sopas. Fácil de limpiar y duradera.', 1),
    ('Reloj Inteligente', 129.99, 'Reloj inteligente con pantalla táctil a color, monitor de actividad y notificaciones inteligentes. Resistente al agua y compatible con dispositivos iOS y Android.', 2),
    ('Mochila Portátil', 39.99, 'Mochila portátil con compartimentos acolchados para laptops y tabletas. Diseño moderno y duradero para llevar tus dispositivos de manera segura.', 2),
    ('Altavoces Bluetooth', 59.99, 'Altavoces Bluetooth inalámbricos con sonido de alta calidad. Batería recargable de larga duración y diseño compacto para llevar la música a donde vayas.', 2),
    ('Batería Externa', 29.99, 'Batería externa de alta capacidad para cargar dispositivos móviles en movimiento. Diseño delgado y portátil para mantener tus dispositivos siempre encendidos.', 2),
    ('Botella de Agua Inteligente', 19.99, 'Botella de agua inteligente con recordatorio de hidratación y seguimiento del consumo de agua. Ideal para aquellos que desean mantenerse hidratados', 2),
    ('Juego de Sábanas de Algodón', 39.99, 'Juego de sábanas suaves y transpirables de algodón. Incluye sábana bajera, sábana encimera y fundas de almohada. Disponible en varios colores.', 3),
    ('Cafetera de Goteo', 59.99, 'Cafetera programable de goteo para preparar café caliente y delicioso. Capacidad para 12 tazas y función de temporizador para disfrutar de café recién hecho.', 3),
    ('Set de Utensilios de Cocina', 29.99, 'Set completo de utensilios de cocina de acero inoxidable. Incluye cucharas, espátulas y otros utensilios esenciales para cocinar.', 3),
    ('Lámpara de Mesa LED', 24.99, 'Lámpara de mesa LED con ajuste de brillo y temperatura de color. Diseño moderno y eficiente energéticamente para iluminar tu espacio de trabajo o lectura.', 3),
    ('Juego de Toallas de Baño', 49.99, 'Juego de toallas de baño de alta calidad y absorbentes. Incluye toallas de baño, toallas de mano y toallas de cara. Disponible en varios colores.', 3),
    ('Aspiradora Robot', 199.99, 'Aspiradora robot inteligente con navegación automática y capacidad de succión potente. Programable para limpieza programada y control a través de aplicación móvil.', 3),
    ('Mesa de Centro de Madera', 129.99, 'Mesa de centro elegante y duradera hecha de madera maciza. Diseño moderno con espacio de almacenamiento adicional para revistas y accesorios.', 3),
    ('Cortinas Opacas', 34.99, 'Cortinas opacas de alta calidad que bloquean la luz y proporcionan privacidad. Disponibles en diferentes tamaños y colores para adaptarse a cualquier estilo de decoración.', 3),
    ('Set de Cuchillos de Cocina', 69.99, 'Set profesional de cuchillos de cocina con hojas de acero inoxidable afiladas. Incluye cuchillo de chef, cuchillo para pan y otros cuchillos esenciales.', 3),
    ('Alfombra de Área', 79.99, 'Alfombra de área suave y duradera para añadir calidez y estilo a cualquier habitación. Disponible en diferentes tamaños y patrones para complementar la decoración.', 3),
    ('Organizador de Zapatos', 19.99, 'Organizador de zapatos colgante con varios compartimentos. Maximiza el espacio de almacenamiento en el armario y mantiene tus zapatos ordenados y accesibles.', 3),
    ('Mesa Plegable para Laptop', 49.99, 'Mesa plegable para laptop ajustable en altura. Perfecta para trabajar o estudiar desde la cama o el sofá. Ligera y fácil de transportar.', 3),
    ('Aire Acondicionado Portátil', 299.99, 'Aire acondicionado portátil con control remoto y función de temporizador. Refresca eficientemente habitaciones pequeñas y se mueve fácilmente de una habitación a otra.', 3),
    ('Espejo de Pared', 89.99, 'Espejo de pared decorativo con marco elegante. Añade estilo y amplitud visual a cualquier habitación. Fácil de instalar y resistente.', 3),
    ('Set de Ollas y Sartenes', 129.99, 'Set completo de ollas y sartenes antiadherentes de alta calidad. Adecuado para todas las fuentes de calor y fácil de limpiar. Ideal para cocina diaria.', 3),
    ('Humidificador Ultrasónico', 39.99, 'Humidificador ultrasónico silencioso para mejorar la calidad del aire. Diseño moderno y capacidad ajustable para adaptarse a diferentes tamaños de habitación.', 3),
    ('Funda de Almohada Decorativa', 14.99, 'Funda de almohada decorativa con patrones elegantes. Añade un toque de estilo a tu sofá o cama. Cierre de cremallera para fácil lavado.', 3),
    ('Mesa de Noche con Cajón', 69.99, 'Mesa de noche compacta con cajón de almacenamiento. Ideal para guardar tus artículos esenciales junto a la cama. Diseño moderno y funcional.', 3),
    ('Cesta de Lavandería', 19.99, 'Cesta de lavandería plegable y portátil. Fabricada con materiales duraderos y asas para facilitar el transporte. Mantiene la ropa sucia organizada y fuera de la vista.', 3),
    ('Arroz Integral', 2.99, 'Arroz integral de grano largo, fuente rica en fibra y nutrientes esenciales para una dieta equilibrada.', 4),
    ('Pasta de Trigo Integral', 1.99, 'Pasta de trigo integral de alta calidad. Ideal para preparar comidas saludables y nutritivas.', 4),
    ('Aceite de Oliva Extra Virgen', 9.99, 'Aceite de oliva extra virgen de primera prensada. Aporta sabor y beneficios para la salud a tus platos.', 4),
    ('Quinoa Orgánica', 4.99, 'Quinoa orgánica de alta calidad, rica en proteínas y nutrientes esenciales. Perfecta para ensaladas y platos principales.', 4),
    ('Miel Pura de Abeja', 7.99, 'Miel pura de abeja, endulzante natural con propiedades antioxidantes y beneficios para la salud.', 4),
    ('Lentejas Secas', 3.49, 'Lentejas secas, fuente de proteínas y fibra. Ideales para sopas, guisos y platos vegetarianos.', 4),
    ('Nueces Naturales', 8.99, 'Nueces naturales sin cáscara, ricas en grasas saludables y antioxidantes. Snack nutritivo y delicioso.', 4),
    ('Salsa de Tomate Orgánica', 2.79, 'Salsa de tomate orgánica, elaborada con tomates frescos y sin aditivos artificiales. Perfecta para pasta y pizzas.', 4),
    ('Cereal Integral', 3.29, 'Cereal integral enriquecido con vitaminas y minerales. Desayuno saludable y energético para empezar el día.', 4),
    ('Sal Marina', 1.49, 'Sal marina natural sin refinar. Aporta minerales esenciales y realza el sabor de tus comidas.', 4),
    ('Vinagre Balsámico', 5.99, 'Vinagre balsámico de alta calidad, perfecto para aderezar ensaladas y platos gourmet.', 4),
    ('Galletas Integrales', 3.79, 'Galletas integrales con granos enteros y bajo contenido de azúcar. Snack saludable para cualquier momento del día.', 4),
    ('Sopa Instantánea de Pollo', 1.99, 'Sopa instantánea de pollo, lista en minutos. Deliciosa y reconfortante para días ocupados.', 4),
    ('Almendras Naturales', 6.49, 'Almendras naturales, ricas en grasas saludables y proteínas. Snack nutritivo para saciar el hambre.', 4),
    ('Puré de Tomate', 2.29, 'Puré de tomate concentrado, versátil para diversas recetas de salsas y guisos.', 4),
    ('Yogur Griego Natural', 3.99, 'Yogur griego natural, rico en proteínas y probióticos. Ideal para desayunos y meriendas saludables.', 4),
    ('Harina de Avena', 4.49, 'Harina de avena integral, perfecta para preparar panes, galletas y batidos nutritivos.', 4),
    ('Aceitunas Verdes', 2.89, 'Aceitunas verdes sin hueso, ideales para aperitivos y ensaladas. Aportan sabor mediterráneo a tus platos.', 4),
    ('Mantequilla de Almendra', 7.99, 'Mantequilla de almendra natural, sin aditivos ni azúcares añadidos. Fuente de grasas saludables y proteínas.', 4),
    ('Jugo de Naranja Natural', 3.49, 'Jugo de naranja fresco y natural, rico en vitamina C. Refrescante y nutritivo para cualquier momento del día.', 4),
    ('Huevos Orgánicos', 4.99, 'Huevos orgánicos de gallinas criadas en libertad. Fuente de proteínas y nutrientes esenciales.', 4),
    ('Salsa de Soja', 1.79, 'Salsa de soja natural, perfecta para dar sabor a platos asiáticos y marinadas.', 4),
    ('Puré de Manzana Sin Azúcar', 2.59, 'Puré de manzana sin azúcar añadido, saludable y versátil para acompañar desayunos y postres.', 4),
    ('Pistachos Tostados', 5.49, 'Pistachos tostados y salados, snack delicioso y nutritivo. Aporta energía y grasas saludables.', 4),
    ('Café Orgánico enGrano', 8.99, 'Café orgánico en grano, tostado y molido fresco para una taza de café aromático y sostenible.', 4),
    ('Sopa de Lentejas en Lata', 2.19, 'Sopa de lentejas enlatada, lista para calentar y disfrutar. Nutritiva y reconfortante en días ocupados.', 4),
    ('Puré de Aguacate', 3.99, 'Puré de aguacate natural, sin conservantes ni aditivos. Perfecto para untar en pan, tacos o como complemento en ensaladas.', 4),
    ('Chocolate Negro 70%', 4.79, 'Tableta de chocolate negro con un 70% de cacao. Delicioso y lleno de antioxidantes. Ideal para satisfacer los antojos de chocolate.', 4),
    ('Muesli de Frutas y Frutos Secos', 3.99, 'Muesli de frutas y frutos secos, mezcla nutritiva para un desayuno lleno de energía. Sin azúcares añadidos.', 4),
    ('Sopa de Tomate en Lata', 1.89, 'Sopa de tomate enlatada, lista para calentar y disfrutar. Sabor casero sin complicaciones.', 4),
    ('Sésamo Tostado', 2.29, 'Sésamo tostado, añade un toque de sabor y textura a tus platos. Ideal para ensaladas y platos asiáticos.', 4),
    ('Mermelada de Fresa Sin Azúcar', 3.49, 'Mermelada de fresa sin azúcar añadido, perfecta para untar en pan o acompañar yogur. Endulza tus mañanas de manera saludable.', 4),
    ('Granola Orgánica', 4.99, 'Granola orgánica con frutas y frutos secos. Añade textura y sabor a tus desayunos y meriendas.', 4),
    ('Té Verde Orgánico', 2.99, 'Té verde orgánico, lleno de antioxidantes y beneficios para la salud. Una opción saludable y reconfortante para tus momentos de relajación.', 4),
    ('Masa para Pizza Integral', 3.79, 'Masa para pizza integral, lista para usar. Añade un toque saludable a tus pizzas caseras.', 4),
    ('Salsa Pesto', 4.29, 'Salsa pesto fresca y deliciosa, perfecta para pasta, ensaladas y como dip. Aporta sabor mediterráneo a tus platos.', 4),
    ('Canela Molida', 1.39, 'Canela molida de alta calidad, ideal para dar sabor a postres, batidos y bebidas calientes.', 4),
    ('Agua Mineral Natural', 0.99, 'Agua mineral natural, refrescante y sin aditivos. La opción perfecta para mantenerte hidratado.', 4),
    ('Balón de Fútbol', 14.99, 'Balón de fútbol de alta calidad. Diseño duradero y apto para partidos recreativos y entrenamientos.', 5),
    ('Raqueta de Tenis', 29.99, 'Raqueta de tenis profesional con tecnología avanzada. Ideal para jugadores intermedios y avanzados.', 5),
    ('Bicicleta de Montaña', 299.99, 'Bicicleta de montaña resistente con cuadro de aluminio. Perfecta para aventuras off-road y senderismo.', 5),
    ('Pesa Ajustable', 49.99, 'Set de pesas ajustables para entrenamiento de fuerza. Variedad de pesos en un diseño compacto y fácil de usar.', 5),
    ('Cinta de Correr Eléctrica', 699.99, 'Cinta de correr eléctrica con motor potente. Programas de entrenamiento personalizables y monitor de ritmo cardíaco.', 5),
    ('Patines en Línea', 79.99, 'Patines en línea ajustables con ruedas de alto rendimiento. Ideales para patinaje recreativo y paseos en el parque.', 5),
    ('Pelota de Baloncesto', 19.99, 'Pelota de baloncesto oficial para juegos y entrenamientos. Agarre superior y durabilidad para un rendimiento óptimo.', 5),
    ('Guantes de Levantamiento de Pesas', 19.99, 'Guantes acolchados para levantamiento de pesas. Proporcionan agarre y protección durante tus sesiones de entrenamiento.', 5),
    ('Gafas de Natación', 12.99, 'Gafas de natación antiempañantes con ajuste cómodo. Diseñadas para proporcionar claridad y visión en el agua.', 5),
    ('Tabla de Surf', 249.99, 'Tabla de surf de alta calidad para surfistas de todos los niveles. Diseño resistente y estable para un rendimiento óptimo en el agua.', 5),
    ('Raqueta de Bádminton', 24.99, 'Raqueta de bádminton ligera y resistente. Apta para jugadores principiantes y intermedios.', 5),
    ('Máquina de Entrenamiento Abdominal', 89.99, 'Máquina de entrenamiento abdominal con resistencia ajustable. Ideal para fortalecer y tonificar los músculos abdominales.', 5),
    ('Casco de Ciclismo', 34.99, 'Casco de ciclismo con diseño aerodinámico y sistema de ventilación. Brinda protección y comodidad durante tus paseos en bicicleta.', 5),
    ('Pelota Medicinal', 14.99, 'Pelota medicinal para ejercicios de fuerza y ​​equilibrio. Ideal para entrenamiento funcional y rehabilitación.', 5),
    ('Máquina de Remo', 299.99, 'Máquina de remo con resistencia ajustable. Proporciona un entrenamiento cardiovascular y de fuerza de cuerpo completo.', 5),
    ('Pantalones de Yoga', 29.99, 'Pantalones de yoga transpirables y elásticos. Ideales para prácticas de yoga y otras actividades deportivas.', 5),
    ('Saco de Boxeo', 79.99, 'Saco de boxeo resistente con cadenas para colgar. Perfecto para entrenamiento de boxeo y ejercicios de acondicionamiento físico.', 5),
    ('Gorra de Running', 14.99, 'Gorra de running ligera y transpirable. Protege del sol y absorbe la humedad durante tus carreras al aire libre.', 5),
    ('Cuerda para Saltar', 9.99, 'Cuerda para saltar ajustable para entrenamientos cardiovasculares. Ligera y portátil para llevar a cualquier lugar.', 5),
    ('Mancuernas', 39.99, 'Set de mancuernas de peso variable. Perfectas para ejercicios de fuerza y tonificación en casa o en el gimnasio.', 5),
    ('Rodilleras de Volleyball', 19.99, 'Rodilleras acolchadas para jugadores de vóley. Brindan protección y soporte durante los juegos y entrenamientos intensos.', 5),
    ('Cámara de Acción', 129.99, 'Cámara de acción resistente al agua para grabar tus aventuras deportivas. Captura videos y fotos de alta calidad durante tus actividades al aire libre.', 5),
    ('Zapatillas de Trail Running', 69.99, 'Zapatillas de trail running con suela antideslizante. Diseñadas para correr en terrenos irregulares y senderos.', 5),
    ('Red de Tenis', 49.99, 'Red de tenis portátil para juegos recreativos. Fácil de montar y desmontar para llevar a cualquier lugar.', 5),
    ('Cinta de Yoga', 14.99, 'Cinta de yoga resistente y antideslizante. Ideal para estiramientos y prácticas de yoga en casa o en el estudio.', 5),
    ('Tablero de Equilibrio', 19.99, 'Tablero de equilibrio para mejorar la estabilidad y fortalecer los músculos centrales. Ideal para entrenamientos en casa o en el gimnasio.', 5),
    ('Cuerda de Escalada', 89.99, 'Cuerda de escalada resistente y duradera. Apta para escaladores principiantes y avanzados.', 5),
    ('Sudadera con Capucha para Running', 34.99, 'Sudadera con capucha transpirable y ligera. Diseñada para mantenerte abrigado durante tus carreras al aire libre.', 5),
    ('Pelota de Yoga', 16.99, 'Pelota de yoga duradera para fortalecimiento y estiramientos. Ideal para mejorar la postura y la flexibilidad.', 5),
    ('Linterna Frontal LED para Running', 24.99, 'Linterna frontal LED recargable para correr de noche. Proporciona visibilidad y seguridad durante tus carreras nocturnas.', 5);


INSERT INTO Clientes (Avatar, Nombre, username, Apellidos, Contrasenia, Correo, Telefono, Direccion) 
VALUES
('https://i.blogs.es/1039bf/langostinos/450_1000.jpg', 'Oiher', 'oiherPerron', 'Oleaga Guerrero', '5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5', 'oiheroleaga@email.com', '657659280', 'calle guetaria, vitoria-gasteiz'),
('https://i.pinimg.com/originals/f5/b3/b7/f5b3b7a64c253f882bfdd4337c7721ac.jpg', 'David', 'DavidMamalon', 'Moreno Alonso', '5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5', 'davidcaca@gmail.com', '9876543210', 'coronela ibaibarriaga, vitoria-gasteiz'),
('https://images3.memedroid.com/images/UPLOADED578/5fbfcb10c4a8c.jpeg', 'Anartz', 'a', 'Pagaldai', 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb', 'pedro@email.com', '5555555555', 'Albacete');

INSERT INTO Categorias (Nombre) VALUES
    ('Tecnologia'),
    ('Hogar'),
    ('Alimentacion'),
    ('Deportes');


INSERT INTO Categorias_Productos (ID_Categorias, ID_Producto) VALUES
    (1, 1), 
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (1, 8),
    (1, 9),
    (1, 10),
    (1, 11),
    (1, 12),
    (1, 13),
    (1, 14),
    (1, 15),
    (1, 16),
    (1, 17),
    (1, 18),
    (1, 19),
    (1, 20),
    (1, 21),
    (1, 22),
    (1, 23),
    (1, 24),
    (1, 25),
    (1, 26),
    (2, 27),
    (2, 28),
    (2, 29),
    (2, 30),
    (2, 31),
    (2, 32),
    (2, 33),
    (2, 34),
    (2, 35),
    (2, 36),
    (2, 37),
    (2, 38),
    (2, 39),
    (2, 40),
    (2, 41),
    (2, 42),
    (2, 43),
    (2, 44),
    (2, 45),
    (2, 46),
    (3, 47),
    (3, 48),
    (3, 49),
    (3, 50),
    (3, 51),
    (3, 52),
    (3, 53),
    (3, 54),
    (3, 55),
    (3, 56),
    (3, 57),
    (3, 58),
    (3, 59),
    (3, 60),
    (3, 61),
    (3, 62),
    (3, 63),
    (3, 64),
    (3, 65),
    (3, 66),
    (3, 67),
    (3, 68),
    (3, 69),
    (3, 70),
    (3, 71),
    (3, 72),
    (3, 73),
    (3, 74),
    (3, 75),
    (3, 76),
    (4, 77),
    (4, 78),
    (4, 79),
    (4, 80),
    (4, 81),
    (4, 82),
    (4, 83),
    (4, 84),
    (4, 85),
    (4, 86),
    (4, 87),
    (4, 88),
    (4, 89),
    (4, 90),
    (4, 91),
    (4, 92),
    (4, 93),
    (4, 94),
    (4, 95),
    (4, 96),
    (4, 97),
    (4, 98),
    (4, 99),
    (4, 100),
    (4, 101),
    (4, 102),
    (4, 103),
    (4, 104),
    (4, 105),
    (4, 106);
    


-- Insertar datos en la tabla Fotos_producto
INSERT INTO Fotos_producto (ID_Producto, URL) VALUES
    (1, 'https://media.game.es/COVERV2/3D_L/186/186150.png'),
    (1, 'https://media.game.es/COVERV2/3D_L/186/186150.png'),
    (1, 'https://media.game.es/COVERV2/3D_L/186/186150.png'),
    (1, 'https://media.game.es/COVERV2/3D_L/186/186150.png'),
    (1, 'https://media.game.es/COVERV2/3D_L/186/186150.png'),
    (2, 'https://m.media-amazon.com/images/I/31KrKAKoLrL._SL500_.jpg'),
    (2, 'https://m.media-amazon.com/images/I/31KrKAKoLrL._SL500_.jpg'),
    (2, 'https://m.media-amazon.com/images/I/31KrKAKoLrL._SL500_.jpg'),
    (2, 'https://m.media-amazon.com/images/I/31KrKAKoLrL._SL500_.jpg'),
    (2, 'https://m.media-amazon.com/images/I/31KrKAKoLrL._SL500_.jpg'),
    (3, 'https://m.media-amazon.com/images/I/31aNiWCZlQL._AC_UF894,1000_QL80_.jpg'),
    (4, 'https://media.game.es/COVERV2/3D_L/P04/P04566.png'),
    (5, 'https://media.game.es/COVERV2/3D_L/P04/P04560.png'),
    (6, 'https://media.game.es/COVERV2/3D_L/V1G/V1GQYE.png'),
    (7, 'https://media.game.es/COVERV2/3D_L/100/100774.png'),
    (8, 'https://media.game.es/COVERV2/3D_L/221/221099.png'),
    (9, 'https://media.game.es/COVERV2/3D_L/088/088706.png'),
    (10, 'https://media.game.es/COVERV2/3D_L/201/201389.png'),
    (11, 'https://media.game.es/COVERV2/3D_L/182/182523.png'),
    (12, 'https://media.game.es/COVERV2/3D_L/V1G/V1GFX5.png'),
    (13, 'https://media.game.es/COVERV2/3D_L/167/167575.png'),
    (14, 'https://media.game.es/COVERV2/3D_L/221/221331.png'),
    (15, 'https://media.game.es/COVERV2/3D_L/225/225019.png'),
    (16, 'https://media.game.es/COVERV2/3D_L/199/199933.png'),
    (17, 'https://media.game.es/COVERV2/3D_L/117/117685.png'),
    (18, 'https://media.game.es/COVERV2/3D_L/V1G/V1GVNC.png'),
    (19, 'https://media.game.es/COVERV2/3D_L/220/220187.png'),
    (20, 'https://media.game.es/COVERV2/3D_L/V1G/V1G0Q8.png'),
    (21, 'https://media.game.es/COVERV2/3D_L/V1G/V1GDOU.png'),
    (22, 'https://media.game.es/COVERV2/3D_L/215/215635.png'),
    (23, 'https://media.game.es/COVERV2/3D_L/209/209763.png'),
    (24, 'https://media.game.es/COVERV2/3D_L/189/189588.png'),
    (25, 'https://media.game.es/COVERV2/3D_L/V00/V006C9.png'),
    (26, 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/HPAS2_AV2?wid=2000&hei=2000&fmt=jpeg&qlt=90&.v=1654034079729');